name: Build MeshAugmentor

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for the release (e.g., v1.2.3)'
        required: true
      prerelease:
        description: 'Mark release as prerelease'
        type: boolean
        required: false
        default: false
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Linux toolchain ---
      - name: Setup build environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libomp-dev make

      # --- Windows toolchain ---
      - name: Setup build environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          choco install -y make
          choco install -y mingw

      # --- Build ---
      - name: Build native library
        run: |
          cd cpp
          make

      # --- Package Linux ---
      - name: Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          set -eux
          STAGE="dist/linux"
          mkdir -p "$STAGE/mesh_augmentor/_lib" "$STAGE/mesh_augmentor"

          cp cpp/*.so "$STAGE/mesh_augmentor/_lib/"

          cp mesh_augmentor/__init__.py mesh_augmentor/mesh_augmentor.py mesh_augmentor/deformations.py "$STAGE/mesh_augmentor/"

          cd "$STAGE"
          zip -r "../../mesh_augmentor-linux.zip" .

      # --- Package Windows ---
      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          $stage = "dist\\windows"
          New-Item -ItemType Directory -Force -Path "$stage\\mesh_augmentor_lib" | Out-Null
          New-Item -ItemType Directory -Force -Path "$stage\\mesh_augmentor" | Out-Null

          Copy-Item "cpp\\*.dll" "$stage\\mesh_augmentor\\_lib\\" -Force

          $gpp = (Get-Command g++.exe -ErrorAction Stop).Source
          $mingwRoot = Split-Path (Split-Path $gpp) -Parent
          $bins = Join-Path $mingwRoot 'bin'
          foreach ($dll in @('libgomp-1.dll','libgcc_s_seh-1.dll','libwinpthread-1.dll')) {
            $src = Join-Path $bins $dll
            if (Test-Path $src) { Copy-Item $src "$stage\\mesh_augmentor\\_lib\\" -Force }
          }

          Copy-Item "mesh_augmentor\\__init__.py","mesh_augmentor\\mesh_augmentor.py","mesh_augmentor\\deformations.py" "$stage\\mesh_augmentor\\" -Force

          if (Test-Path "mesh_augmentor-windows.zip") { Remove-Item "mesh_augmentor-windows.zip" -Force }
          Compress-Archive -Path "$stage\\*" -DestinationPath "mesh_augmentor-windows.zip" -Force

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mesh_augmentor-${{ matrix.os }}
          path: |
            mesh_augmentor-linux.zip
            mesh_augmentor-windows.zip
          if-no-files-found: ignore

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          draft: false
          prerelease: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.prerelease || false }}
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            mesh_augmentor-linux.zip
            mesh_augmentor-windows.zip
